clean:
	-rm *.aux \
	*-dot2tex* \
	*.pdf \
	*.dot \
	*.fdb_latexmk \
	*.fls \
	*.synctex.gz \
	*.bbl \
	*.blg \
	*.dvi \
	*.eps_ \
	*.idx \
	*.ind \
	*.jpg \
	*.lof \
	*.log \
	*.lot \
	*.out \
	*.ps \
	*.tex_bak \
	*.toc 2>/dev/null
